services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coachera-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coachera
    depends_on:
      - db

  db:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=coachera'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=coachera'
    ports:
      - 5432:5432
